# Generated by Django 2.0.7 on 2019-12-27 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20191227_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='facultyname',
        ),
        migrations.RemoveField(
            model_name='job',
            name='url1',
        ),
    ]
