# Generated by Django 2.0.7 on 2019-12-27 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20191227_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='facultyname',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
